In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# load the data
transactions = pd.read_csv('../data/transactions_history_final.csv')

In [5]:
transactions.head()

,gitOutlet_ID,Year,Month,Distributor_ID,SKU_ID,Volume_Liters,Total_Bill_Value
0,OUT_19886,2024,12,DIST_S_02,SKU_10,5.897879,2177.632359
1,OUT_00837,2024,2,DIST_W_01,SKU_03,20.697364,7244.084814
2,OUT_15438,2025,12,DIST_NW_01,SKU_02,55.101801,13959.108790
3,OUT_12992,2025,1,DIST_C_01,SKU_07,24.063953,15641.548770
4,OUT_12334,2025,5,DIST_C_02,SKU_04,47.769665,15525.158660

In [6]:
transactions.to_parquet(
    "../data/bronze/transactions.parquet"
)

In [7]:
outletMaster = pd.read_csv('../data/outlet_master.csv')

In [8]:
outletMaster.head()

   Outlet_ID Outlet_Size  Cooler_Count Outlet_Type
0  OUT_00001      Medium             1      Grocry
1  OUT_00002       Small             0       Hotel
2  OUT_00003       Small             1    Pharmacy
3  OUT_00004      Medium             2    Pharmacy
4  OUT_00005      Medium             2       Kiosk

In [9]:
outletMaster.to_parquet(
    "../data/bronze/outletMaster.parquet"
)

In [11]:
outletCoordinates = pd.read_csv('../data/outlet_coordinates.csv')

In [12]:
outletCoordinates.head()

   Outlet_ID  Latitude  Longitude
0  OUT_00001  7.089846  79.979055
1  OUT_00002  7.000558  80.012422
2  OUT_00003  6.806170  79.854547
3  OUT_00004  6.703533  79.806919
4  OUT_00005  7.186878  79.869831

In [13]:
outletCoordinates.to_parquet(
    "../data/bronze/outletCoordinates.parquet")

In [14]:
holidays = pd.read_csv('../data/holiday_list.csv')

In [15]:
holidays.head()

,Date,Holiday_Name,Holiday_Type
0,2023-01-06T00:00:00Z,Duruthu Full Moon Poya Day,Public
1,2023-01-15T00:00:00Z,Tamil Thai Pongal Day,Public
2,2023-01-16T00:00:00Z,Additional Holiday in lieu of Tamil Thai Ponga...,Public
3,2023-02-03T00:00:00Z,Additional Half Holiday in lieu of the Indepen...,Public
4,2023-02-04T00:00:00Z,National Day,Public

In [16]:
holidays.to_parquet(
    "../data/bronze/holidays.parquet")

In [17]:
seasonality = pd.read_csv('../data/distributor_seasonality_details.csv')

In [18]:
seasonality.head()

  Distributor_ID  Year  Month Seasonality_Index
0      DIST_W_01  2023      1          Moderate
1      DIST_W_01  2023      2          Moderate
2      DIST_W_01  2023      3          Moderate
3      DIST_W_01  2023      4         Favorable
4      DIST_W_01  2023      5      Un-Favorable

In [19]:
seasonality.to_parquet(
    "../data/bronze/seasonality.parquet")