In [205]:
import pandas as pd


transactions = pd.read_csv(
    "../data/bronze/transactions.csv"
)

transactions.head()

,gitOutlet_ID,Year,Month,Distributor_ID,SKU_ID,Volume_Liters,Total_Bill_Value
0,OUT_19886,2024,12,DIST_S_02,SKU_10,5.897879,2177.632359
1,OUT_00837,2024,2,DIST_W_01,SKU_03,20.697364,7244.084814
2,OUT_15438,2025,12,DIST_NW_01,SKU_02,55.101801,13959.108790
3,OUT_12992,2025,1,DIST_C_01,SKU_07,24.063953,15641.548770
4,OUT_12334,2025,5,DIST_C_02,SKU_04,47.769665,15525.158660

In [206]:
transactions.columns

Index(['gitOutlet_ID', 'Year', 'Month', 'Distributor_ID', 'SKU_ID',
       'Volume_Liters', 'Total_Bill_Value'],
      dtype='object')

In [207]:
#Remove Duplicate Rows
transactions = transactions.drop_duplicates(
    subset=[
        "gitOutlet_ID",
        "Year",
        "Month",
        "Distributor_ID",
        "SKU_ID"
    ]
)

In [208]:
#Remove Missing Values
transactions = transactions.dropna(
    subset=[
        "gitOutlet_ID",
        "Distributor_ID",
        "SKU_ID",
        "Volume_Liters"
    ]
)

In [209]:
#Remove Invalid Sales Volumes
transactions = transactions[
    transactions["Volume_Liters"] >= 0
]

In [210]:
#Remove Invalid Bill Values
transactions = transactions[
    transactions["Total_Bill_Value"] >= 0
]

In [211]:
#Remove Invalid Year
transactions = transactions[
    (transactions["Year"] >= 2020) &
    (transactions["Year"] <= 2026)
]

In [212]:
#Remove Invalid Month
transactions = transactions[
    (transactions["Month"] >= 1) &
    (transactions["Month"] <= 12)
]

In [213]:
#Save Clean Transactions
transactions.to_csv(
    "../data/silver/clean_transactions.csv",
    index=False
)

In [214]:
transactions.shape

(1039959, 7)

In [215]:
holidays = pd.read_csv(
    "../data/bronze/holidays.csv"
)

holidays.head()

,Unnamed: 0,Date,Holiday_Name,Holiday_Type
0,0,2023-01-06T00:00:00Z,Duruthu Full Moon Poya Day,Public
1,1,2023-01-15T00:00:00Z,Tamil Thai Pongal Day,Public
2,2,2023-01-16T00:00:00Z,Additional Holiday in lieu of Tamil Thai Ponga...,Public
3,3,2023-02-03T00:00:00Z,Additional Half Holiday in lieu of the Indepen...,Public
4,4,2023-02-04T00:00:00Z,National Day,Public

In [216]:
holidays.columns

Index(['Unnamed: 0', 'Date', 'Holiday_Name', 'Holiday_Type'], dtype='object')

In [217]:
#Convert Date Column
holidays["Date"] = pd.to_datetime(
    holidays["Date"],
    errors="coerce"
)

In [218]:
#Remove Invalid Dates
holidays = holidays[
    holidays["Date"].notnull()
]

In [219]:
#Remove Duplicate Rows
holidays = holidays.drop_duplicates()

In [220]:
#Remove Missing Holiday Names
holidays = holidays.dropna(
    subset=["Holiday_Name"]
)

In [221]:
#Remove Missing Holiday Types
holidays = holidays.dropna(
    subset=["Holiday_Type"]
)

In [222]:
#Save Clean Holiday Dataset
holidays.to_csv(
    "../data/silver/clean_holidays.csv",
    index=False
)

In [223]:
coordinates = pd.read_csv(
    "../data/bronze/outletCoordinates.csv"
)

coordinates.head()

   Outlet_ID  Latitude  Longitude
0  OUT_00001  7.089846  79.979055
1  OUT_00002  7.000558  80.012422
2  OUT_00003  6.806170  79.854547
3  OUT_00004  6.703533  79.806919
4  OUT_00005  7.186878  79.869831

In [224]:
coordinates.columns

Index(['Outlet_ID', 'Latitude', 'Longitude'], dtype='object')

In [225]:
#Remove Duplicate Outlets
coordinates = coordinates.drop_duplicates(
    subset=["Outlet_ID"]
)

In [226]:
#Remove Missing Values
coordinates = coordinates.dropna(
    subset=[
        "Outlet_ID",
        "Latitude",
        "Longitude"
    ]
)

In [227]:
#Convert Coordinates to Numeric
coordinates["Latitude"] = pd.to_numeric(
    coordinates["Latitude"],
    errors="coerce"
)

coordinates["Longitude"] = pd.to_numeric(
    coordinates["Longitude"],
    errors="coerce"
)

In [228]:
#Remove Invalid Latitude
coordinates = coordinates[
    (coordinates["Latitude"] >= 5) &
    (coordinates["Latitude"] <= 10)
]

In [229]:
#Remove Invalid Longitude
coordinates = coordinates[
    (coordinates["Longitude"] >= 79) &
    (coordinates["Longitude"] <= 82)
]

In [230]:
#Save Clean Dataset
coordinates.to_csv(
    "../data/silver/clean_outletCoordinates.csv",
    index=False
)

In [231]:
coordinates.shape

(19760, 3)

In [232]:
import pandas as pd

outlets = pd.read_csv(
    "../data/bronze/outletMaster.csv"
)

outlets.head()

   Outlet_ID Outlet_Size  Cooler_Count Outlet_Type
0  OUT_00001      Medium             1      Grocry
1  OUT_00002       Small             0       Hotel
2  OUT_00003       Small             1    Pharmacy
3  OUT_00004      Medium             2    Pharmacy
4  OUT_00005      Medium             2       Kiosk

In [233]:
outlets.columns

Index(['Outlet_ID', 'Outlet_Size', 'Cooler_Count', 'Outlet_Type'], dtype='object')

In [234]:
#Remove Duplicate Outlets
outlets = outlets.drop_duplicates(
    subset=["Outlet_ID"]
)

In [235]:
#Remove Missing Outlet_ID
outlets = outlets.dropna(
    subset=["Outlet_ID"]
)

In [236]:
#Remove Negative Cooler Counts
outlets = outlets[
    outlets["Cooler_Count"] >= 0
]

In [237]:
#Fill Missing Outlet_Size
outlets["Outlet_Size"] = outlets[
    "Outlet_Size"
].fillna("Unknown")

In [238]:
#Fill Missing Outlet_Type
outlets["Outlet_Type"] = outlets[
    "Outlet_Type"
].fillna("Unknown")

In [239]:
#Remove Extra Spaces
outlets["Outlet_Size"] = outlets[
    "Outlet_Size"
].str.strip()

outlets["Outlet_Type"] = outlets[
    "Outlet_Type"
].str.strip()

In [240]:
#Save Clean Dataset
outlets.to_csv(
    "../data/silver/clean_outlet_master.csv",
    index=False
)

In [241]:
outlets.shape

(20000, 4)

In [242]:
import pandas as pd

seasonality = pd.read_csv(
    "../data/bronze/seasonality.csv"
)

seasonality.head()

   Unnamed: 0 Distributor_ID  Year  Month Seasonality_Index
0           0      DIST_W_01  2023      1          Moderate
1           1      DIST_W_01  2023      2          Moderate
2           2      DIST_W_01  2023      3          Moderate
3           3      DIST_W_01  2023      4         Favorable
4           4      DIST_W_01  2023      5      Un-Favorable

In [243]:
seasonality.columns

Index(['Unnamed: 0', 'Distributor_ID', 'Year', 'Month', 'Seasonality_Index'], dtype='object')

In [244]:
#Remove Duplicate Rows
seasonality = seasonality.drop_duplicates(
    subset=[
        "Distributor_ID",
        "Year",
        "Month"
    ]
)

In [245]:
#Remove Missing Values
seasonality = seasonality.dropna(
    subset=[
        "Distributor_ID",
        "Year",
        "Month",
        "Seasonality_Index"
    ]
)

In [246]:
#Remove Invalid Years
seasonality = seasonality[
    (seasonality["Year"] >= 2020) &
    (seasonality["Year"] <= 2026)
]

In [247]:
#Remove Invalid Months
seasonality = seasonality[
    (seasonality["Month"] >= 1) &
    (seasonality["Month"] <= 12)
]

In [248]:
#Save Clean Dataset
seasonality.to_csv(
    "../data/silver/clean_seasonality.csv",
    index=False
)

In [249]:
seasonality.shape

(360, 5)